const projects = [
    {
        name: "testName",
        description: "testDescription",
        type: "testType",
        language: "testLanguage",
        image: "testImage",
        alt: "testAlt",
        url: "https://google.com/",
        githubURL: "https://github.com",
        id: 1,
    },
    {
        name: "testName2",
        description: "testDescription2",
        type: "testType2",
        language: "testLanguage2",
        image: "testImage2",
        alt: "testAlt2",
        url: "https://google.com/",
        githubURL: "https://github.com/",
        id: 2,
    },
    {
        name: "testName3",
        description: "testDescription3",
        type: "testType3",
        language: "testLanguage3",
        image: "testImage3",
        alt: "testAlt3",
        url: "https://google.com/",
        githubURL: "https://github.com/",
        id: 3,
    },
    {
        name: "testName4",
        description: "testDescription4",
        type: "testType4",
        language: "testLanguage4",
        image: "testImage4",
        alt: "testAlt4",
        url: "https://google.com/",
        githubURL: "https://github.com/",
        id: 4,
    },
    {
        name: "testName5",
        description: "testDescription5",
        type: "testType5",
        language: "testLanguage5",
        image: "testImage5",
        alt: "testAlt5",
        url: "https://google.com/",
        githubURL: "https://github.com/",
        id: 5,
    },
];

export default projects;
